baseURL = "https://example.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Vasilij Melnychuk personal homepage"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Vasilij Melnychuk"
  email = "vasilij@melnychuk.me"
  description = "Personal homepage"
  bio = "Software Developer"
  avatar = "img/avatar.png"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/sqrel"
    instagram = "https://instagram.com/sqrel"
    twitter = "https://twitter.com/sqrel"
    linkedin = "https://www.linkedin.com/in/sqrel/"
    telegram = "https://t.me/sqrel/"
